/**
 * Generates `app/routes.gen.ts` from the contents of `app/routes/`.
 *
 * Subset of React Router's flat routes convention we support:
 *   _index.tsx           → index route ("/")
 *   text.tsx             → "/text"
 *   foo.bar.tsx          → "/foo/bar"   (dot = path separator)
 *   $id.tsx              → "/:id"       (dynamic segment)
 *   $.tsx                → "/*"         (splat)
 *   _layout.tsx          → pathless segment (ignored in the path)
 *
 * Filenames may end in .tsx / .jsx / .ts / .js.
 */
import { readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const ROUTES_DIR = join(here, "..", "app", "routes");
const OUT = join(here, "..", "app", "routes.gen.ts");

const files = readdirSync(ROUTES_DIR)
  .filter((f) => /\.(tsx|jsx|ts|js)$/.test(f))
  .sort();

type Route = {
  importName: string;
  importPath: string;
  index: boolean;
  path: string;
};

function pascalCase(input: string): string {
  const parts = input.split(/[^a-zA-Z0-9]+/).filter(Boolean);
  if (!parts.length) return "Route";
  return parts.map((p) => p[0]!.toUpperCase() + p.slice(1)).join("");
}

const used = new Set<string>();
function uniqueName(base: string): string {
  let name = base || "Route";
  let i = 2;
  while (used.has(name)) name = `${base}${i++}`;
  used.add(name);
  return name;
}

const routes: Route[] = files.map((file) => {
  const base = file.replace(/\.(tsx|jsx|ts|js)$/, "");
  const importPath = `./routes/${base}`;

  if (base === "_index") {
    return {
      importName: uniqueName("Index"),
      importPath,
      index: true,
      path: "",
    };
  }

  const segments = base
    .split(".")
    .map((seg) => {
      if (seg === "$") return "*";
      if (seg.startsWith("$")) return `:${seg.slice(1)}`;
      if (seg.startsWith("_")) return null; // pathless
      return seg;
    })
    .filter((s): s is string => s !== null);

  return {
    importName: uniqueName(pascalCase(base)),
    importPath,
    index: false,
    path: segments.join("/"),
  };
});

// Index route is eager (tiny, always shown on "/").
// All other routes are lazy-loaded via React.lazy so their JS chunks
// (including large deps like CodeMirror) are only fetched when visited.
const eagerRoutes = routes.filter((r) => r.index);
const lazyRoutes = routes.filter((r) => !r.index);

const header = `// AUTO-GENERATED by scripts/generate-routes.ts — do not edit by hand.\n`;
const eagerImports = eagerRoutes
  .map((r) => `import ${r.importName} from "${r.importPath}";`)
  .join("\n");
const lazyImports = lazyRoutes
  .map(
    (r) =>
      `const ${r.importName} = lazyWithRetry(() => import("${r.importPath}"));`,
  )
  .join("\n");
const entries = routes
  .map((r) =>
    r.index
      ? `  { index: true, Component: ${r.importName} },`
      : `  { path: ${JSON.stringify(r.path)}, Component: ${r.importName} },`,
  )
  .join("\n");

const body = `${header}import { lazyWithRetry } from "./lib/lazy-with-retry";
import type { RouteObject } from "react-router";
${eagerImports}
${lazyImports}

export const routes: RouteObject[] = [
${entries}
];
`;

writeFileSync(OUT, body);
console.log(`Generated ${OUT} (${routes.length} routes)`);
